# Generated by Django 3.1 on 2020-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/addcars')),
                ('carType', models.CharField(max_length=50)),
                ('carCompany', models.CharField(max_length=100)),
                ('carName', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('kmDriven', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/sellcars')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('carType', models.CharField(max_length=50)),
                ('carCompany', models.CharField(max_length=100)),
                ('carName', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('kmDriven', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
