# Generated by Django 3.1 on 2020-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcar',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellcar',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
