# Generated by Django 3.1 on 2020-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200809_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='image',
            field=models.ImageField(upload_to='assets/media/addcars'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='image',
            field=models.ImageField(upload_to='assets/media/sellcars'),
        ),
    ]
