# Generated by Django 3.1 on 2020-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200809_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='addcar',
            name='image',
            field=models.ImageField(upload_to='addcars'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='image',
            field=models.ImageField(upload_to='sellcars'),
        ),
    ]
